const STEPS=[
 // ---- FIRST — the F1 league texts (so Claude can build the app) ----
 {id:'f1tools',d:1,t:'F1 league (1 of 2) — install the little tool that reads Messages',m:10,why:'Fifteen years of Steve\'s hand-tallied picks live in the F1 group in Messages on this Mac. Claude can\'t see the Mac, so we export the thread once. Step 1 installs a free, well-known tool (imessage-exporter). One paste, one password, one switch.',
  need:'This Mac (the one with the F1 group in Messages) and your Mac password.',
  copy:'/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"\nBREW=$(ls /opt/homebrew/bin/brew /usr/local/bin/brew 2>/dev/null | head -1)\necho "eval \\"\\$($BREW shellenv)\\"" >> ~/.zprofile\neval "$($BREW shellenv)"\nbrew install imessage-exporter',
  steps:['Open Terminal: press ⌘ Space, type Terminal, press Enter','Tap 📋 Copy the message above → click inside Terminal → ⌘V → press Enter','It asks for your Mac password (nothing shows while you type — normal) → Enter. It may also say "Press RETURN to continue" → Enter. Then wait; 2–5 minutes is normal','When the cursor comes back, tap the Full Disk Access link below → System Settings opens → find Terminal in the list and switch it ON (not there? click ＋ → Applications → Utilities → Terminal)','Quit Terminal (⌘Q) and open it again — the switch only counts after a restart'],
  links:[['🔓 Full Disk Access (opens System Settings)','x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles'],['What is imessage-exporter?','https://github.com/ReagentX/imessage-exporter'],['What is Homebrew?','https://brew.sh']]},
 {id:'f1export',d:1,t:'F1 league (2 of 2) — export the F1 thread and drop it in Google Drive',m:5,why:'This writes every chat to a folder on your Desktop as plain text. We only care about the F1 one. It goes in Drive, not the app site — the thread has fifteen years of the guys\' personal talk in it and Drive keeps it private. Then Claude writes the rulebook, you check it, and the app gets built.',
  need:'Step 1 finished. Your Google sign-in.',
  copy:'imessage-exporter -f txt -c disabled -o ~/Desktop/f1-export',
  steps:['Tap 📋 Copy the message above → click inside Terminal → ⌘V → Enter → wait until the cursor comes back (a few minutes)','Says "command not found"? Paste this instead:  /opt/homebrew/bin/imessage-exporter -f txt -c disabled -o ~/Desktop/f1-export','Finder → Desktop → open the f1-export folder → find F1.txt (named after the group; if it isn\'t there, look for the file whose name has Steve, Ryan, Mark and Robbi in it)','Tap Google Drive below → ＋ New → File upload → Desktop → f1-export → F1.txt → Open','Text Claude: "F1 file is in Drive" — I take it from there'],
  links:[['📁 Google Drive','https://drive.google.com/drive/my-drive']]},
 // ---- TODAY — the testing morning ----
 {id:'teststore',d:1,t:'Walk the store as a stranger with a wallet',m:40,why:'The store wears its 🧪 TEST FLIGHT stripes now. New since you last walked it: the "Not sure where to start?" quiz, name subtitles on every card, ✨ NEW LOOK badges, church videos, FlipKit. Talk everything into Feedback Studio as you go.',
  steps:['Open the store → read it like a buyer','Tap the quiz → does it point you right?','Play 2–3 videos — the voice is smooth now; flag any line that still stumbles','Send me the Feedback Studio report'],
  links:[['🛍 The store','https://jerrywins1.github.io/daraja-apps/shop/'],['🎙 Feedback Studio','https://jerrywins1.github.io/daraja-apps/feedback-studio/']]},
 {id:'testnn',d:1,t:'Now & Next v7.5 — your photo, the codes, the coach',m:15,why:'River is the real app now. Your copy is grandfathered (badge says ✓ yours). Set your own photo with 📷 My photo, cycle 🎨 Look, and watch a first-time coach card pop.',
  steps:['Open it fresh (close + reopen once for the newest)','📷 My photo → pick a family picture','🎨 Look → all three outfits → land where you like'],
  links:[['▶ Now & Next','https://jerrywins1.github.io/daraja-apps/Apps%20(installable%20site)/nownext/']]},
 {id:'flip',d:1,t:'FlipKit — flip ONE real thing from the garage',m:10,why:'The product test that pays for lunch. Add a thing, tap "Price it with my AI", paste the answer back, copy the listing to Marketplace.',
  steps:['Add the thing you almost sold last spring','🤖 Price it with my AI → attach a photo in ChatGPT/Claude → paste the reply back','📋 Copy the listing → paste on Facebook Marketplace'],
  links:[['💸 FlipKit','https://jerrywins1.github.io/daraja-apps/flipkit/']]},
 {id:'invite',d:1,t:'Text your 3–4 testers: the link + the word TESTING',m:5,why:'That one text IS the invitation. TESTING = 30 days, then the app locks kindly until they buy or you extend. Their stuff is never lost.',
  copy:'I built an app I think your family might love — it\'s called Now & Next, one thing at a time for busy brains. Here\'s the link: https://jerrywins1.github.io/daraja-apps/Apps%20(installable%20site)/nownext/ — when it asks for a code, type TESTING. That gives you 30 days. Tell me everything, good and bad!',
  steps:['Copy the message below','Text it to your 3–4 people']},
 // ---- OPEN THE STORE (money plumbing) ----
 {id:'gumroad',d:2,t:'Gumroad — payment, then paste the 3 listings',m:30,why:'Step 0 of the Launch Day Playbook. The copy is written — you paste. When the buy links exist, send them to me and launch becomes one word.',
  steps:['gumroad.com → finish account + payout','Paste listings from Daraja Studio/Store/Gumroad Listings — ready to paste.md','Send Claude the product links'],
  links:[['gumroad.com','https://gumroad.com']]},
 {id:'domain',d:2,t:'Register darajastudio.com',m:10,why:'$12/year. The brand\'s address.',need:'A credit card.',
  steps:['Cloudflare or Namecheap → search darajastudio.com → buy 1 year → auto-renew on','Taken? darajastudio.co — text me which you got'],
  links:[['Cloudflare','https://www.cloudflare.com/products/registrar/'],['Namecheap','https://www.namecheap.com']]},
 {id:'llc',d:2,t:'File the Illinois LLC ($150)',m:30,why:'The liability shield; the bank needs it. Online, approved in days.',need:'Home address as registered agent, a card.',
  steps:['ilsos.gov → Business Services → File Articles of Organization (LLC-5.5)','Name: Daraja Studio LLC · member-managed','Pay $150 → save the confirmation PDF to Daraja Studio/Legal/'],
  links:[['ilsos.gov LLC filing','https://www.ilsos.gov/departments/business_services/organization/llc_instructions.html']]},
 {id:'ein',d:2,t:'EIN — free, 10 minutes (after LLC approves)',m:10,why:'The company\'s tax number. IRS only; ignore paid sites.',
  steps:['irs.gov EIN Online → LLC → started new business','Download the CP-575 letter IMMEDIATELY (shows once) → Daraja Studio/Legal/'],
  links:[['IRS EIN Online','https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online']]},
 {id:'george',d:2,t:'Email George the CPA',m:5,why:'One email now saves a tax-season surprise.',
  copy:'George — I\'ve started a small online business, Daraja Studio LLC (Illinois). Selling digital templates and small apps; profits go to the Loving InDeed scholarships as a personal donation, not an org link. Two questions when you have a minute: (1) anything I should set up now for clean books — separate account is coming; (2) does the scholarship donation plan change anything? Thanks — Jerry',
  steps:['Tap Copy below → email it to George']},
 {id:'bank',d:2,t:'Business bank account (when LLC + EIN exist)',m:45,why:'Keeps Daraja money separate — the one thing George will insist on.',need:'LLC approval, EIN letter, driver\'s license.',
  steps:['Relay or Mercury (free, online, ~15 min) — or your own bank\'s business checking','Upload LLC + EIN + ID','Text me the last 4 digits only when open']},
 // ---- WITH PEOPLE ----
 {id:'pilotchurch',d:3,t:'Show one church the Care Plan page',m:10,why:'The recurring-money engine needs one pilot church. The page makes the argument for you: own it $149 + $29/mo care, vs the platforms\' $300–1,500/mo hostage model.',
  steps:['Open the page yourself once','Send it to your church contact (or show it at the demo meeting)','Tell me who and I prep anything they ask'],
  links:[['⛪ The Care Plan page','https://jerrywins1.github.io/daraja-apps/church/care/']]},
 {id:'pilotadvisor',d:3,t:'Pick the pilot advisor for Keepsake',m:10,why:'One coffee meeting. The sample gift page does the selling — an advisor sees "A gift from Hendricks Wealth" once and imagines their own name on it. First pilot is free for a testimonial + three introductions.',
  steps:['Open the advisor page, then the sample gift','Think of your own money people — who first?','Text me the name; I brand their sample page before the meeting'],
  links:[['💼 Keepsake Pro','https://jerrywins1.github.io/daraja-apps/keepsake/'],['🎁 The sample gift','https://jerrywins1.github.io/daraja-apps/keepsake/sample/']]},
 {id:'dickson',d:3,t:'Ask Dickson two things (Kenya)',m:5,why:'He gates the whole Kenya side — the graduates AND the Duka manager question.',
  copy:'Dickson — two things when you have a minute. 1) We\'re building a way for graduates to earn online through our store; who are two sharp graduates who\'d try it this week? 2) For the little shared-shop idea (kids resell from one stocked room) — who would you trust to run the room and the M-Pesa till? Asante.',
  steps:['Copy → WhatsApp Dickson']},
 {id:'diane',d:3,t:'In Good Order with Diane (20 minutes together)',m:20,why:'The most important 20 minutes on this list.',
  steps:['Open it together → pick the family passphrase → write it on paper where she knows','Fill "Call these people first" and "Where the papers are"','Print → fire safe'],
  links:[['In Good Order','https://claude.ai/code/artifact/d314b4c3-2346-4a03-b8c3-913db447c996']]},
 {id:'counselor',d:3,t:'Ask for the Safety Plan wording review',m:5,why:'Free forever, in Ryan\'s memory — the words must be right first.',
  copy:'We built a small pocket safety-plan app (Stanley-Brown format) to give away free, in memory of my son Ryan. Before we share it anywhere, would you read every word and tell us what to change? I\'ll send the link.',
  steps:['Copy → send to your LCSPTF contact or a counselor'],
  links:[['My Safety Plan','https://jerrywins1.github.io/daraja-apps/Apps%20(installable%20site)/safety/']]},
 {id:'walkpub',d:3,t:'Walk publicity — Sept 26 is close',m:15,why:'Flyers and notices around town: libraries, coffee shops, counseling offices, churches. Say the word and I draft the flyer + the target list.',
  steps:['Tell Claude: "draft the walk flyer and the list of places"','Review, add places you know','Print → drop off / call'],
  links:[['The sign-up link','https://runsignup.com/Race/Register/RaceGroup-2131426?raceId=166657']]},
 // ---- DECISIONS PARKED FOR YOU (1 minute each — just text me the word) ----
 {id:'d_careplan',d:4,t:'Decide: Care Plan — "Care Plan yes" or "hold"',m:1,why:'The $29/mo church service. Page is built; pilot church is the next domino.',steps:['Text me the word']},
 {id:'d_keepsake',d:4,t:'Decide: Keepsake — "Pilot it" or "Park it"',m:1,why:'The advisor gifting channel ($99/mo or $497 packs). Pages are built.',steps:['Text me the word']},
 {id:'d_dailyword',d:4,t:'Decide: Daily Word — "Build" or "Park"',m:1,why:'Your church-communication idea: devotions + announcements inside The Church App, calendar-subscribe reminders, zero servers. Brief is written.',steps:['Text me the word']},
 {id:'d_safety',d:4,t:'Decide: My Safety Plan on the shelf — keep or hold?',m:1,why:'It shows as COMING on the church shelf. Keep it listed, or hide until the counselor review?',steps:['Text me the word']},
 // ---- WHENEVER ----
 {id:'aheaditems',d:5,t:'Ahead of It — put your real life in it',m:10,why:'You are customer #1. Boat, pontoon, golf cart, LTC, Medicare, the 990 — guesses are fine, fix later. ⚡ Quick setup does it on one screen.',
  steps:['Open the app → ⚡ Quick setup','Tick everything that is yours → real dates → Save'],
  links:[['🧭 Ahead of It','https://jerrywins1.github.io/daraja-apps/Apps%20(installable%20site)/ahead/']]},
 {id:'mykey',d:5,t:'Fill out YOUR OWN Key — print two',m:15,why:'You\'re the first customer; you\'ll feel what needs fixing. One printed page: where everything is.',
  links:[['🔑 The Key','https://jerrywins1.github.io/daraja-apps/thekey/']],steps:['Fill it in','Print two — fire safe + Diane']},
 {id:'gqdeck',d:5,t:'Print the Grand Questions deck at home',m:10,why:'Hold the cards. If they feel right, they go to Printify — and into every Keepsake box.',
  steps:['Print from Daraja Studio/Grand Questions/','Pull one card at dinner with Diane 😊']},
 {id:'zuri',d:5,t:'Zuri HQ deploy (5 minutes, for Dickson & Kelvin)',m:5,why:'One paste at script.google.com and the Zuri phones feed the HQ dashboard.',
  need:'Your Google sign-in. The file: Zuri Fiber CFO → Zuri Ops App → HQ_Collector_AppsScript.gs',
  steps:['script.google.com → New project → delete the sample','Paste the file contents → Save','Deploy → Web app → Execute as Me → Anyone → copy URL','Paste the URL into Zuri Ops Settings and the HQ dashboard'],
  links:[['script.google.com','https://script.google.com/home']]},
 {id:'ryan',d:5,t:'Ryan\'s channel: do you have his Google sign-in?',m:2,why:'Yes → Takeout backup + add you as manager. No → Google\'s deceased-user request. Everything else waits on this.',
  steps:['Check your records / password book','Text me yes or no — I map the next step either way']},
];