/* Daraja Store — one shared catalog. v1.6 · 2026-08-30 (+ success endings; scene-directed + pointing finger — the app changes screens with the story)
   To add an app to the store: add one entry here. The shelf card AND its
   2-minute video come from this data — nothing else to build. */
const BASE = 'https://jerrywins1.github.io/daraja-apps/';
const A = BASE + 'Apps%20(installable%20site)/';

const APPS = {
 nownext: {
  name:'Now & Next', em:'🧭', fresh:true, cat:'family', price:'$4.99', testing:true,
  tag:'One thing at a time — for kids and grown-ups whose brains run fast',
  try:A+'nownext/', video:true,
  train:[
   "Let's set up Now and Next — five minutes, then it runs your mornings forever.",
   "Step one: when it opens, add each person in your family — kid or grown-up. Tap a name in the header any time to switch people.",
   {t:"Step two: add a task. Type one small thing in the box and tap Add. Tap the words of any task to make it the NOW.", js:"try{go('today')}catch(e){}"},
   "Step three: the NOW card shows one thing, with a timer. Do it, check it off — and enjoy the party. That's the whole engine.",
   {t:"Step four: routines. Open Routines and regulars, and turn on Morning, Homework, or Bedtime. They'll show up by themselves at the right time of day — no nagging.", js:"try{go('routines')}catch(e){}", point:"#n-routines"},
   {t:"Step five: tap the little calendar button to plan the whole week. Type things like 'doctor Tuesday' — it pins the day itself. Tap Spread the week, then Send, and everything lands on the right day for the right person.", js:"try{go('today');document.getElementById('wkBtn')&&document.getElementById('wkBtn').click()}catch(e){}", point:"#wkBtn"},
   {t:"Step six: make it yours. Tap My photo and pick a picture you love — the grandkids, the lake — and your whole day floats on glass over it. Tap Look to change outfits: River, Warm Paper, or Quest H U D game mode. Tap A a to make the words bigger.", js:"try{go('today')}catch(e){}"},
   {t:"And don't worry about learning it — the first time you touch any feature, a little card pops up and explains it, and it can even read itself out loud. Tap Got it and it never bothers you again."},
   {t:"Last: peek at Wins now and then — coins, streaks, and the family leaderboard live there. That's it. One thing at a time.", js:"try{var o=document.getElementById('wkOv');o&&(o.style.display='none');go('wins')}catch(e){}"},
   "You'll know it's set up right when the NOW card shows one thing with a timer — and somebody checks it off and gets the party."],
  lines:[
   "This is Now and Next — for kids, and grown-ups, whose brains run fast.",
   "The problem it solves: knowing exactly what to do… and still not being able to start. And the parent who's said 'hurry up' eleven times before seven thirty.",
   "Here's how it works. The screen shows ONE thing — the thing to do now. Not the whole scary list. Just one.",
   "A timer makes the middle short. And when you finish? It throws a little party. High fives, coins, a leaderboard for the family.",
   "Mornings, homework and bedtime run on routines that show up by themselves — no nagging required.",
   "Everyone in the family gets their own list, their own coins, their own buddy — the whole family on one phone.",
   "And it's getting smart. The new week planner lets you empty your head — laundry, appointments, visits — then spreads the whole week onto sensible days for everyone, in one tap.",
   "It even notices on its own: four days in a row, don't break the chain. Two more finishes your best day ever. A helper on your shoulder, not a boss.",
   "The benefit is simple: kids start, kids finish, and nobody yells. Calmer mornings are worth a lot more than five dollars.",
   "It's four ninety-nine, once. No account, no ads, works offline, nothing leaves your phone.",
   "Try it right now with the button below — and see what your morning could sound like.",
  'New: big jobs get broken into pieces you can actually start — a six-hour garage becomes eight little wins.',
  'And Horizons: once a week, your grown-up\'s AI finds gentle doors near you — the open gym, the beginner chess night. No feed. No pressure.',
  'And the brand-new River look: your own family photo becomes the background, your day floats over it on glass — with a timeline that shows when things happen. Three looks to choose from, including a game mode with X P for the teenagers.',
  'New features explain themselves the first time you touch them — a little card, in plain words, that can read itself out loud.']},
 ahead: {
  name:'Ahead of It', em:'🧾', fresh:true, cat:'family', price:'$9', testing:true,
  tag:'Taxes, renewals, the dog\'s shots — know what it costs you to miss one',
  try:A+'ahead/', video:true,
  train:[
   "Setting up Ahead of It takes five minutes, once — then nothing catches you off guard again.",
   {t:"Step one: open the library and tap the items your house actually has — taxes, plate renewals, insurance, the dog's shots.", js:"try{go('lib')}catch(e){}", point:"nav button[data-v='lib']"},
   "Step two: put in your real dates. For each one, the app shows what missing it would cost you — that's how you know what matters.",
   {t:"Step three: make Sunday your glance day. The thirty-days-out view tells you everything that's coming before it can surprise you.", js:"try{go('next')}catch(e){}", point:"nav button[data-v='next']"},
   {t:"Step four: look at the year map once — your whole year of obligations on one screen.", js:"try{go('year')}catch(e){}", point:"nav button[data-v='year']"},
   {t:"Step five: fill in the hand-off list. If you're ever not the one carrying the household, someone can pick it up without detective work. Done.", js:"try{go('more')}catch(e){}"},
   "You'll know you're set when the front page shows your next thirty days, with dates that are really yours — and nothing on it surprises you."],
  lines:[
   "This is Ahead of It — for whoever carries the household.",
   "The problem: taxes, plate renewals, insurance, the dog's shots. Each one causes real problems if you miss it — and they all live in your head.",
   "How it works: a library of twenty-seven things households forget, ready to add in one tap. Your real dates, your real stuff.",
   "It shows you what's due in the next thirty days — and exactly what it costs you to miss each one, so you know what actually matters.",
   "There's a year map so you can see the whole calendar of obligations at a glance.",
   "And a hand-off list — so if you're ever not the one carrying the household, someone else can pick it up without detective work.",
   "The benefit: nothing catches you off guard. No late fees, no lapsed insurance, no 'I thought YOU renewed it.'",
   "Nine dollars, once. One missed late fee costs more.",
   "Try it below — add three real things from your own house and feel the difference."]},
 nextstep: {
  name:'Next Step Board', em:'🗂', fresh:true, cat:'work', price:'$9', testing:true,
  tag:'Every project, its next step, whose turn — one screen',
  try:A+'nextstep/', video:true,
  train:[
   "Next Step Board setup — five minutes with your coffee.",
   "Step one: add every project you're juggling. Work, home, church — all of them, one screen.",
   "Step two: for each project write ONE next step, and whose turn it is — yours, or someone you're waiting on.",
   "Step three: set priorities and due dates so the important things float to the top.",
   "Step four: every morning, open the board and just go down the list. Add anything new in one tap.",
   "Step five: when a step gets done, write the next one right away. Projects never stall when the next step is always written. That's the whole secret.",
   "You'll know it's working when every project on the board has a next step written. No blanks — blanks are where projects go to sleep."],
  lines:[
   "This is Next Step Board — for anyone juggling more than three projects.",
   "The problem: projects don't stall because they're hard. They stall because nobody wrote down the NEXT STEP.",
   "How it works: one screen. Every project you've got, its very next step, and whose turn it is — yours or someone you're waiting on.",
   "Priorities and due dates keep the important things on top. A 'coming up' bar shows what's about to land.",
   "Add a task in one tap, send a date to your calendar in one tap.",
   "Sit down with your coffee, open the board, and go down the list — business person or household manager, it's the same relief.",
   "The benefit: nothing stalls, nothing gets forgotten, and you always know what to do next.",
   "Nine dollars, once. No subscription, no account, works offline.",
   "Try it below — put your three real projects in and watch your morning get simpler."]},
 breakeven: {
  name:'Break-Even', em:'🧮', cat:'free', price:'Free', testing:false,
  tag:'Price your product — see exactly when you start making money',
  try:A+'breakeven/', video:true,
  train:[
   "Using Break-Even — two minutes to the truth.",
   "Step one: what does one unit cost you to make? Supplies, materials — the honest number.",
   "Step two: what do you sell it for? And what does selling cost — the table fee, the listing fee, shipping?",
   "Step three: read the answer. It shows the exact sale where you cross into profit.",
   "Step four: slide the price up and down and watch the break-even point move. That's how you pick a price on purpose instead of by guess.",
   "You'll know it worked when you can say out loud: 'I make money on number twelve.' That sentence is the whole product."],
  lines:[
   "This is Break-Even — free, for anyone selling anything.",
   "The problem: you made a thing, you picked a price… but you honestly don't know when you start making money.",
   "How it works: put in your costs, your price, what each sale takes out — it shows the exact number of sales where you cross into profit.",
   "Slide the price up and down and watch the break-even point move. Suddenly pricing isn't a guess.",
   "The benefit: you stop selling at a loss without knowing it. Every craft-fair table and side hustle needs this once.",
   "It's completely free — our gift, and a taste of how we build.",
   "Try it below with your real numbers. It takes two minutes to know the truth."]},
 safety: {
  name:'My Safety Plan', em:'🫶', cat:'free', price:'Free forever', testing:false,
  tag:'A private safety plan in your pocket — built in memory of Ryan',
  try:A+'safety/', video:true,
  train:[
   "Filling out My Safety Plan — do this on a calm day, so it's ready on a hard one.",
   "Step one: warning signs. Write what a bad day looks like for you — the thoughts, the feelings, the situations.",
   "Step two: ways to cope. Small things that have helped before — a walk, music, a shower, calling someone.",
   "Step three: your people. Who to talk to, and their numbers — a friend, family, your counselor.",
   "Step four: reasons to stay. In your own words. Take your time on this one.",
   "That's it. It saves privately on your phone, and 'Talk to someone now' is always one tap — nine-eight-eight. If you love someone who struggles, fill it out together."],
  lines:[
   "This is My Safety Plan. It's free, forever — built in memory of Ryan.",
   "It's a private safety plan in the proven six-step format counselors use: warning signs, ways to cope, reasons to stay, people to call.",
   "You fill it out on a calm day — so it's there on a hard one.",
   "'Talk to someone now' is one tap: nine-eight-eight, the Suicide and Crisis Lifeline.",
   "It's completely private. No account, nothing leaves your phone.",
   "If you love someone who struggles, put this on their phone together. That's the whole reason it exists.",
   "It will never cost anything. Try it below — or share it with someone who needs it today."]},
 feedback: {
  name:'Feedback Studio', em:'🎙', cat:'work', price:'$12', testing:true,
  tag:'Use an app, talk out loud — your voice becomes the builder\'s to-do list',
  try:BASE+'feedback-studio/', video:true,
  train:[
   "Using Feedback Studio for the first time — here's the whole routine.",
   "Step one: open it in Chrome or Edge. Paste the address of the app you're reviewing and tap Open. The real app appears in the window.",
   "Step two: press the big red button. Your browser will ask about the microphone once — tap Allow.",
   "Step three: use the app and just talk. Pause between thoughts — each pause becomes its own timestamped comment on the right.",
   "Step four: see something on screen worth pointing at? Tap 'Mark this spot' — it drops a flag at that exact moment.",
   "Step five: pick who the report is for — Claude, ChatGPT, Gemini, or your developer — then tap Build the report, Copy, and paste it wherever it needs to go. Five minutes of talking, a week of guessing saved.",
   "You'll know it worked when the report reads your own words back with timestamps. Copy it, send it — that's a finished session."],
  lines:[
   "This is Feedback Studio — for anyone who builds apps, and anyone who tests them.",
   "The problem: feedback is the hardest part of building. People say 'looks good!' — and then don't use the thing.",
   "How it works: the app you're testing opens in a window, working for real. You press one red button… and just talk while you use it.",
   "Every thought becomes a comment, stamped with the exact second you said it. See something? Tap 'mark this spot.'",
   "When you're done, one tap builds a clean report — every comment in order. Hand it to Claude, ChatGPT, or a human developer. It works with any of them.",
   "The benefit: honest feedback in five minutes instead of a meeting nobody schedules. One session can save a week of guessing.",
   "Twelve dollars, once. If you build anything, it pays for itself the first afternoon.",
   "There's a two-minute demo movie on the shelf — or just try it below on any app you like."]},
 storykeeper: {
  name:'In My Own Words', em:'📖', cat:'family', price:'Free app · printed book from $39', testing:true,
  tag:'Their voice, in a book — life stories, photos, and The Key',
  try:BASE+'story-keeper/', video:true,
  train:[
   "Making a book with In My Own Words — here's how a good session goes.",
   "Before you start: sit somewhere quiet, close to the microphone — arm's reach or less. That one habit makes the words come out right.",
   "Step one: add the people of your life — spouse, kids, grandkids. Every story will remember who was there.",
   {t:"Step two: pick a chapter, press the red button, and just talk, like telling a story at the kitchen table. Tap right in the words to fix anything it misheard — or tap Read it back and listen for wrong words.", js:"try{openChap('love')}catch(e){}"},
   "Step three: when the memory is warm, add a picture from that time — the app waits while you find it.",
   "Step four: riffed a bit? Tap Make it book-ready — it helps you polish the telling into book prose without losing your voice.",
   {t:"Step five: fill in The Key at the bottom of the home page. Then tap See your book, and watch a life turn into pages. Save a backup now and then — the button's right there.", js:"try{openBook()}catch(e){}"},
   "You'll know it's working when Your Book shows a cover with their name and one real story beneath it. One story is a book begun."],
  lines:[
   "This is In My Own Words. Their voice… in a book.",
   "The problem: someone you love is full of stories — and one day the stories go with them. And their forty thousand photos? Scattered, unlabeled, unfindable.",
   "How it works: sit down together. The app asks a gentle question — 'tell me about the day you met your sweetheart.' They press the red button and just talk.",
   "Their words are written down exactly as they said them. Then the app asks: 'do you have a picture from this time? I'll wait.' Story by story, the photos that matter come out of the pile.",
   "Every story remembers who was in it — so a grandchild can one day read every story that has THEM in it.",
   "And at the back: The Key — one page that tells the family where all the pictures and accounts live. So nothing is lost.",
   "It all becomes a real printed book. Cover, chapters, photos, their exact words.",
   "The app is free. The printed book starts at thirty-nine dollars — and it's the gift nobody ever forgets getting.",
   "Try it below. Ask someone you love one question tonight."]},
 academy: {
  name:'Daraja Academy', em:'🌉', cat:'family', price:'Lesson 1 free · course $19', testing:true,
  tag:'AI for Grandparents — learn to use AI, the patient way',
  try:BASE+'academy/', video:true,
  train:[
   "Taking a Daraja Academy lesson — here's all there is to it.",
   {t:"Sit somewhere comfortable, sound on. Every page has a 'read this page to me' button — tap it and just listen.", js:"try{go(0)}catch(e){}"},
   {t:"Go one screen at a time with the big Next button. Nothing you tap can break anything — that's a promise.", js:"try{go(1)}catch(e){}"},
   {t:"When the lesson asks you to try something, try it — that's where the learning lives.", js:"try{go(3)}catch(e){}"},
   {t:"At the end, print your certificate. And yes — send a picture of it to the grandkids.", js:"try{db.name=db.name||'Grandma';go(7)}catch(e){}"}],
  lines:[
   "This is Daraja Academy — starting with A I for Grandparents.",
   "The problem: the whole world is talking about A I… and nobody is patiently teaching the people who didn't grow up with it.",
   "How it works: big print, one thing at a time, and every page can read itself out loud. Like a patient grandson showing you, not a manual.",
   "Lesson one: Just Ask It. In ten minutes you'll talk to an A I for the first time — safely, right inside the lesson. You can't break anything.",
   "You'll learn the only rule that matters: talk to it like a person, not a computer.",
   "And the grandparent safety rule — how to spot the phone scams that copy a grandchild's voice. That lesson alone is worth the course.",
   "You finish with a printable certificate: 'I speak A I.' Send a picture to the grandkids. Frame it.",
   "Lesson one is free. The full course will be nineteen dollars — and it's a beautiful gift for a parent or grandparent.",
   "Try lesson one below. It only takes ten minutes to feel ten years younger."]},
 thekey: {
  name:'The Key', em:'🔑', cat:'free', price:'Free forever', testing:false,
  try:BASE+'thekey/', video:true,
  train:[
   "Filling out The Key — five minutes for a lifetime of relief.",
   {t:"Box one: where your pictures live. Phones, clouds, albums in the closet — and who can get in.", js:"try{var c=document.querySelectorAll('.card')[0];c&&c.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){}"},
   {t:"Box two: accounts that matter. Write where the passwords are KEPT — the notebook, the safe — never the passwords themselves.", js:"try{var c=document.querySelectorAll('.card')[1];c&&c.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){}"},
   {t:"Box three: the papers. Will, deed, insurance — the drawer, the safe, the lawyer's name.", js:"try{var c=document.querySelectorAll('.card')[2];c&&c.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){}"},
   {t:"Box four: the people who know things. The lawyer, the accountant, the grandson who does computers.", js:"try{var c=document.querySelectorAll('.card')[3];c&&c.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){}"},
   {t:"Then tap Print my Key, and print two: one for the drawer, one for the person you trust most. Update it when life changes — the date prints on the page.", js:"", point:".btn.wide"},
   "You'll know it's done when the printed page is in the drawer and the person you trust has their copy. That's the whole job — finished in an afternoon."],
  tag:'One page that tells your family where everything lives',
  lines:[
   "This is The Key — free, forever. The most loving page you'll ever print.",
   "The problem: your pictures are on a phone, in a cloud, on an old computer. Your papers are in a drawer somewhere. And the only person who knows where everything is… is you.",
   "The Key is one page: where the pictures live, where the passwords are kept, where the papers are, and who to call.",
   "Five minutes, once. Then print two copies — one for the drawer, one for the person you trust most.",
   "Never the passwords themselves — just where they're kept. And nothing is sent anywhere; it stays on your device.",
   "When the day comes, your family won't have to be detectives. They'll have The Key.",
   "It's free. Fill yours out tonight — and send this to your parents while you're at it."]},
 occ: {
  name:'OCC Box Counter', em:'📦', cat:'free', price:'Free', testing:false,
  tag:'Shoebox-packing inventory — how many boxes can we build?',
  try:A+'occ/', video:true,
  train:[
   "Using the Box Counter at a packing party — here's the routine.",
   "Step one: count what's on the table. Big plus and minus buttons; tap an item's name for plus five and plus ten.",
   "Step two: mark what goes in EVERY box — soap, toothbrush, washcloth — with the 'every box' toggle.",
   "Step three: read the dashboard: READY TO BUILD tells you how many complete boxes you can make, and what you're short on.",
   "Step four: as you pack, count down. When it says you're short on washcloths — that's your shopping list.",
   "You'll know it's working when the dashboard says READY TO BUILD and a number. That number is the whole answer."],
  lines:[
   "This is the OCC Box Counter — free, for shoebox-packing teams.",
   "The problem: a table full of soap, toothbrushes, and toys — and no idea how many complete boxes you can actually build.",
   "How it works: count your items with big plus and minus buttons. Mark what goes in every box.",
   "The dashboard answers the only question that matters: 'READY TO BUILD: this many boxes' — and exactly what you're short on.",
   "Made for Operation Christmas Child packing parties, church tables, and garage inventories.",
   "It's free. Try it below — your next packing day will thank you."]},
 zuri: {
  name:'Zuri Ops', em:'📡', cat:'work', price:'Ask us', testing:false,
  tag:'Field operations for a small ISP — works with no signal',
  try:A+'zuri/', video:true,
  train:[
   "Zuri Ops for the field — the daily rhythm.",
   "Morning: open the app, confirm your float — the cash you're starting with.",
   "During the day: log each expense and payment as it happens. It works with no signal; everything waits.",
   "It learns your habits and warns you before the float runs out.",
   "Friday: the Friday Report builds itself — and when the phone finds internet, everything syncs to the HQ dashboard on its own."],
  lines:[
   "This is Zuri Ops — built for a real internet company in Maai Mahiu, Kenya.",
   "It's field operations on one phone: cash counts, expenses, bills, the Friday Report.",
   "It learns your habits, forecasts when the float runs out, and syncs to a headquarters dashboard whenever it finds internet.",
   "Built for teams that work where the signal doesn't — everything works offline first.",
   "If you run a small field team anywhere in the world, this pattern fits you too. Ask us.",
   "Try the demo below and see a day in the field."]},
 compass: {
  name:'Daraja Compass', em:'🧭', fresh:true, cat:'free', price:'Free', testing:false,
  tag:'A life-mapping interview — talk your way to what matters',
  try:A+'compass/', video:true,
  train:[
   "Using Daraja Compass — give it a quiet evening.",
   "Step one: answer the questions honestly. Tap an example if the words won't come, or press the microphone and just talk.",
   "Step two: don't rush. It asks what a good mentor would ask — where you are, what matters, what's next.",
   "Step three: when you're done, look at your life on one page. Keep it, pray over it, come back in a season and see what moved."],
  lines:[
   "This is Daraja Compass — a life-mapping interview, free.",
   "It asks you the questions a good mentor would: where you are, what matters, what's next.",
   "You can tap example answers — or press the microphone and just talk.",
   "A little daily verse keeps it grounded.",
   "The benefit: an hour with Compass and you can see your own life on one page.",
   "It's free. Try it below when you have a quiet evening."]},
};
